name: Continuous Integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: bamboo_env
        environment-file: environment.yml
        auto-activate-base: true

    - name: Install package
      shell: bash
      run: |
        conda activate bamboo_env
        
        # Check the latest version of Bamboo
        BAMBOO_VERSION=$(curl -s https://api.github.com/repos/CycloneSEQ-Bioinformatics/Bamboo/releases/latest | grep "tag_name" | awk -F'"' '{print $4}' | sed 's/^v//')
        echo $BAMBOO_VERSION 
        
        # Download Bamboo executable
        wget https://github.com/CycloneSEQ-Bioinformatics/Bamboo/releases/download/v$BAMBOO_VERSION/bamboo-$BAMBOO_VERSION.tar.gz
        
        # Unzip
        tar xvzf bamboo-$BAMBOO_VERSION.tar.gz
        
        # Update file permission to allow bamboo to be executed.
        cd bamboo-$BAMBOO_VERSION
        chmod +x bamboo
        export PATH="$PATH:$(pwd)"

    - name: Test help message
      shell: bash
      run: |
        conda activate bamboo_env
        bamboo --help

    - name: Test FASTQ analyses (single input file)
      shell: bash
      run: |
        conda activate bamboo_env
        bamboo --sequence_path test/data/ecoli_hifi.reads.fastq.gz -o test/output/fastq_1 --sample_size 100

    - name: Test FASTQ analyses (multiple input files)
      shell: bash
      run: |
        conda activate bamboo_env
        bamboo --sequence_path test/data/ecoli_hifi.reads.fastq.gz test/data/yeast_reads.fastq.gz -o test/output/fastq_2 --sample_size 100
        
    - name: Test BAM analyses (single thread)
      shell: bash
      run: |
        conda activate bamboo_env
        bamboo --bam_path test/data/yeast_alignment.bam --reference_path test/data/yeast_reference.fasta -o test/output/bam_1 --sample_size 100 --realign -t 1
      
    - name: Test BAM analyses (multiple threads)
      shell: bash
      run: |
        conda activate bamboo_env
        bamboo --bam_path test/data/yeast_alignment.bam --reference_path test/data/yeast_reference.fasta -o test/output/bam_2 --sample_size 100 --realign -t 4
    
    - name: Test FASTQ + reference analyses
      shell: bash
      run: |
        conda activate bamboo_env
        bamboo --sequence_path test/data/ecoli_hifi.reads.fastq.gz --reference_path test/data/ecoli.reference.fasta.gz -o test/output/fastq_reference_1 --sample_size 10000
    
    - name: Test FASTQ + reference analyses (no sampling)
      shell: bash
      run: |
        conda activate bamboo_env
        bamboo --sequence_path test/data/ecoli_hifi.reads.fastq.gz --reference_path test/data/ecoli.reference.fasta.gz -o test/output/fastq_reference_2 --sample_size -1
